"""Shared API contract constants for backend validation + frontend guidance."""

TEAM_NAME_MIN_LENGTH = 1
TEAM_NAME_MAX_LENGTH = 100
CUSTOM_PROMPT_MAX_LENGTH = 500
CHAT_MESSAGE_MIN_LENGTH = 1
CHAT_MESSAGE_MAX_LENGTH = 1000
SEARCH_QUERY_MIN_LENGTH = 1
SEARCH_QUERY_MAX_LENGTH = 200
PREDICTIONS_LIMIT_DEFAULT = 50
PREDICTIONS_LIMIT_MAX = 500

SUPPORTED_SPORTS = ("soccer", "basketball")
